# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  murthy

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'murthy'
    scriptType: 'Bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t cprimemyacr321014.azurecr.io/web-game:tag 2048-game
      az acr login -n cprimemyacr321014
      docker push cprimemyacr321014.azurecr.io/web-game:tag

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       docker build -t cprimemyacr321014.azurecr.io/web-game:tag 2048-game
#       az acr login -n cprimemyacr321014
#       docker push cprimemyacr321014.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'murthy'
    azureResourceGroup: 'prime-rg'
    kubernetesCluster: 'cprimecluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'murthy'
    azureContainerRegistry: 'cprimemyacr321014.azurecr.io'
    forceUpdate: false

# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
#     azureResourceGroup: 'prime-rg'
#     kubernetesCluster: 'cprimecluster'
#     namespace: 'default'
#     command: 'apply'
#     useConfigurationFile: true
#     configuration: '01_kubernetes_aks'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'
#     azureSubscriptionEndpointForSecrets: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
#     azureContainerRegistry: 'cprimemyacr321014.azurecr.io'
#     forceUpdate: false
