# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  terraform1

steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/hello project'
    backendServiceArm: 'aks'
    backendAzureRmResourceGroupName: 'moorthy'
    backendAzureRmStorageAccountName: 'mystoragem'
    backendAzureRmContainerName: 'murthy'
    backendAzureRmKey: 'terraform.tf'